/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sisup.ui;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import sisup.clases.Bomba;
import sisup.controladores.BombasControlador;

/**
 *
 * @author Liz
 */
public class UIAgregarBomba2 extends javax.swing.JPanel {

    public UIAgregarBomba2(final UIDashboard padre) {
        super();
        this.padre = padre;
        initComponents();
        btn_editar.setVisible(false);
        txt_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_agregarBomba = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_accion = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        pnl_usuario = new javax.swing.JPanel();
        lbl_nombres = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        txt_tag = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        cmb_estatus = new javax.swing.JComboBox();
        lbl_estatus = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_nota1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(866, 641));

        pnl_agregarBomba.setOpaque(false);

        pnl_titulo.setOpaque(false);

        lbl_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/agregarNuevaBomba.png"))); // NOI18N
        lbl_titulo.setText("Agregar Bomba");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_accion.setOpaque(false);

        btn_cerrar.setBackground(new java.awt.Color(204, 204, 255));
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/atras.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_cerrar.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_cerrar.setOpaque(false);
        btn_cerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(204, 204, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/agregarNuevaBomba2.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_agregar.setBorderPainted(false);
        btn_agregar.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_agregar.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_agregar.setOpaque(false);
        btn_agregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(204, 204, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/agregarNuevaBomba2.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_editar.setBorderPainted(false);
        btn_editar.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_editar.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_editar.setOpaque(false);
        btn_editar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_editar.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_accionLayout = new javax.swing.GroupLayout(pnl_accion);
        pnl_accion.setLayout(pnl_accionLayout);
        pnl_accionLayout.setHorizontalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_editar)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar)
                .addGap(18, 18, 18)
                .addComponent(btn_cerrar)
                .addContainerGap())
        );
        pnl_accionLayout.setVerticalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cerrar)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la bomba"));
        pnl_usuario.setOpaque(false);

        lbl_nombres.setText("TAG (*):");

        lbl_apellidos.setText("Descripción (*):");

        txt_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tagActionPerformed(evt);
            }
        });

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Desactivado" }));

        lbl_estatus.setText("Estatus:");

        txt_id.setFocusable(false);

        lbl_nota1.setText("Nota: Los campos (*) son obligatorios");

        javax.swing.GroupLayout pnl_usuarioLayout = new javax.swing.GroupLayout(pnl_usuario);
        pnl_usuario.setLayout(pnl_usuarioLayout);
        pnl_usuarioLayout.setHorizontalGroup(
            pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_usuarioLayout.createSequentialGroup()
                        .addComponent(lbl_nombres)
                        .addGap(60, 60, 60)
                        .addComponent(txt_tag, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_usuarioLayout.createSequentialGroup()
                        .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nota1)
                            .addGroup(pnl_usuarioLayout.createSequentialGroup()
                                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_apellidos)
                                    .addComponent(lbl_estatus))
                                .addGap(26, 26, 26)
                                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_usuarioLayout.setVerticalGroup(
            pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuarioLayout.createSequentialGroup()
                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_usuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombres)
                            .addComponent(txt_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_apellidos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_usuarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_estatus))
                    .addGroup(pnl_usuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmb_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(lbl_nota1)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_agregarBombaLayout = new javax.swing.GroupLayout(pnl_agregarBomba);
        pnl_agregarBomba.setLayout(pnl_agregarBombaLayout);
        pnl_agregarBombaLayout.setHorizontalGroup(
            pnl_agregarBombaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_agregarBombaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_agregarBombaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_accion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_agregarBombaLayout.setVerticalGroup(
            pnl_agregarBombaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_agregarBombaLayout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_agregarBomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_agregarBomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        cerrarVista();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        agregarDatosBomba();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        agregarDatosBomba();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JComboBox cmb_estatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_nota1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_accion;
    private javax.swing.JPanel pnl_agregarBomba;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JPanel pnl_usuario;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_tag;
    // End of variables declaration//GEN-END:variables

    UIDashboard padre;
    Bomba bomba;
    BombasControlador bombasControlador;
    boolean modoEditar;
    String mnj_confirmacion = "Se ha agregado la bomba exitosamente";
    String mnj_error = "Ha ocurrido un error agregando la bomba";
    
    public void setModoEditar(Bomba bomba) {
        this.modoEditar = true;
        mostrarDatosEditar(bomba);
        this.lbl_titulo.setText(this.lbl_titulo.getText().replace("Agregar", "Editar"));
        btn_editar.setVisible(true);
        this.btn_agregar.setVisible(false);
        mnj_confirmacion = mnj_confirmacion.replace("agreg", "edit");
        mnj_error = mnj_error.replace("agreg", "edit");
    }
    
    public void setModoAgregar() {
        this.modoEditar = false;
        this.lbl_titulo.setText(this.lbl_titulo.getText().replace("Editar", "Agregar"));
        btn_editar.setVisible(false);
        this.btn_agregar.setVisible(true);
        mnj_confirmacion = mnj_confirmacion.replace("edit", "agreg");
        mnj_error = mnj_error.replace("edit", "agreg");
    }
    
    public void mostrarDatosEditar(Bomba bomba){
        this.txt_tag.setText(bomba.getTag());
        this.txt_descripcion.setText(bomba.getDescripcionTag());
        this.cmb_estatus.setSelectedItem(bomba.getEstatus());
        this.txt_id.setText(bomba.getId());
    }

    private void agregarDatosBomba() {
        if (bombasControlador == null) bombasControlador = new BombasControlador();
        if(ValidarDatos()){
            bomba = bombasControlador.armarBomba(this.txt_id.getText(),
                                                       this.txt_tag.getText(),
                                                       this.txt_descripcion.getText(),
                                                       this.cmb_estatus.getSelectedItem().toString());
            
            if (bombasControlador.agregarDatosBomba(modoEditar,bomba) == 1){
                JOptionPane.showMessageDialog(null, mnj_confirmacion, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                padre.uiBombas.CargarTablaBombas();
                cerrarVista();
            }
            else 
                JOptionPane.showMessageDialog(null, mnj_error, "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        else 
            JOptionPane.showMessageDialog(null, "Por favor complete todos los datos obligatorios", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean ValidarDatos(){
        return !this.txt_tag.getText().isEmpty() && !this.txt_descripcion.getText().isEmpty();
    }
    
    private void cerrarVista(){
        limpiarCampos();
        padre.cambiapanel(UIDashboard.enm_paneles.UIBOMBAS);
    }
    
    private void limpiarCampos(){
        this.txt_tag.setText("");
        this.txt_descripcion.setText("");
        this.cmb_estatus.setSelectedItem("Activo");
        this.txt_id.setText("");
    }
}
