/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sisup.ui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import sisup.controladores.BombasControlador;

/**
 *
 * @author Liz
 */
public class UIBombas extends javax.swing.JPanel {
    
    /**
     * Creates new form IUBombas
     */
    public UIBombas(final UIDashboard padre) {
        super();
        this.padre = padre;
        initComponents();
        CargarTablaBombas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bombas = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_iconoBomba = new javax.swing.JLabel();
        txt_bomba = new javax.swing.JLabel();
        pnl_accion = new javax.swing.JPanel();
        btn_atras = new javax.swing.JButton();
        btn_agregarBomba = new javax.swing.JButton();
        pnl_listadoBombas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bombas = new javax.swing.JTable();

        setOpaque(false);

        pnl_bombas.setOpaque(false);

        pnl_titulo.setOpaque(false);

        lbl_iconoBomba.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_iconoBomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/bombas.png"))); // NOI18N
        lbl_iconoBomba.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txt_bomba.setText("Administrar Bombas");
        txt_bomba.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_iconoBomba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_iconoBomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt_bomba, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_accion.setOpaque(false);

        btn_atras.setBackground(new java.awt.Color(204, 204, 255));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/atras.png"))); // NOI18N
        btn_atras.setText("Atrás");
        btn_atras.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_atras.setBorderPainted(false);
        btn_atras.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_atras.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_atras.setOpaque(false);
        btn_atras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_atras.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        btn_agregarBomba.setBackground(new java.awt.Color(204, 204, 255));
        btn_agregarBomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/agregarBomba.png"))); // NOI18N
        btn_agregarBomba.setText("Agregar");
        btn_agregarBomba.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_agregarBomba.setBorderPainted(false);
        btn_agregarBomba.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_agregarBomba.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_agregarBomba.setOpaque(false);
        btn_agregarBomba.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_agregarBomba.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_agregarBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarBombaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_accionLayout = new javax.swing.GroupLayout(pnl_accion);
        pnl_accion.setLayout(pnl_accionLayout);
        pnl_accionLayout.setHorizontalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_agregarBomba)
                .addGap(18, 18, 18)
                .addComponent(btn_atras))
        );
        pnl_accionLayout.setVerticalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_atras)
                .addComponent(btn_agregarBomba))
        );

        pnl_listadoBombas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Bombas"));
        pnl_listadoBombas.setOpaque(false);

        tbl_bombas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TAG", "Status", "Acción"
            }
        ));
        jScrollPane1.setViewportView(tbl_bombas);

        javax.swing.GroupLayout pnl_listadoBombasLayout = new javax.swing.GroupLayout(pnl_listadoBombas);
        pnl_listadoBombas.setLayout(pnl_listadoBombasLayout);
        pnl_listadoBombasLayout.setHorizontalGroup(
            pnl_listadoBombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_listadoBombasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_listadoBombasLayout.setVerticalGroup(
            pnl_listadoBombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listadoBombasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_bombasLayout = new javax.swing.GroupLayout(pnl_bombas);
        pnl_bombas.setLayout(pnl_bombasLayout);
        pnl_bombasLayout.setHorizontalGroup(
            pnl_bombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bombasLayout.createSequentialGroup()
                .addGroup(pnl_bombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_accion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_bombasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnl_listadoBombas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_bombasLayout.setVerticalGroup(
            pnl_bombasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bombasLayout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_listadoBombas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bombas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_bombas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        padre.cambiapanel(UIDashboard.enm_paneles.UIDASHBOARD);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_agregarBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarBombaActionPerformed
        padre.cambiapanel(UIDashboard.enm_paneles.UIAGREGARBOMBA);
    }//GEN-LAST:event_btn_agregarBombaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarBomba;
    private javax.swing.JButton btn_atras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_iconoBomba;
    private javax.swing.JPanel pnl_accion;
    public javax.swing.JPanel pnl_bombas;
    private javax.swing.JPanel pnl_listadoBombas;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JTable tbl_bombas;
    private javax.swing.JLabel txt_bomba;
    // End of variables declaration//GEN-END:variables
    
    private UIDashboard padre;

    BombasControlador bombasControlador;
    
    public void CargarTablaBombas() {
        if (bombasControlador == null) bombasControlador = new BombasControlador();

        Object[][] data = bombasControlador.getListaBombas();
        
        if(data.length != 0){
            String[] columnNames = {"Descripcion", "Estatus", "Acción"};

            DefaultTableModel model = new DefaultTableModel(data, columnNames);
            JTable table2 = new JTable(model);

            Action delete = new AbstractAction()
            {
                public void actionPerformed(ActionEvent e)
                {
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand());
                    //((DefaultTableModel)table.getModel()).removeRow(modelRow);
                    String var = table.getModel().getValueAt(modelRow, 0).toString();
                    String ac = e.getActionCommand();
                    padre.uiAgregarBomba.setModoEditar(bombasControlador.getBombaEditar(modelRow));
                    padre.cambiapanel(UIDashboard.enm_paneles.UIAGREGARUSUARIO);
                }
            };

            ButtonColumn buttonColumn = new ButtonColumn(table2, delete, 4);
            //buttonColumn.setMnemonic(KeyEvent.VK_D);

            JScrollPane scroll = new JScrollPane(table2);
            scroll.setPreferredSize(new java.awt.Dimension(400, 200));
            pnl_listadoBombas.add(scroll);
            scroll.setVisible(true);
            jScrollPane1.setVisible(false);
            scroll.setBounds(30, 30, 400, 200);
        }
    }
}
