/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sisup.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Rectangle;
import javax.swing.BorderFactory;
import javax.swing.Box;
import sisup.controladores.Dashboard;

/**
 *
 * @author Liz
 */
public class UIDashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public UIDashboard() {
        initComponents();
        iniciarVentanas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp_escritorio = new javax.swing.JDesktopPane();
        pnl_principal = new javax.swing.JPanel();
        pnl_dashboard = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        pnl_tabla = new javax.swing.JPanel();
        pnl_content = new javax.swing.JScrollPane();
        tbl_resumenReportes = new javax.swing.JTable();
        men_menu = new javax.swing.JMenuBar();
        mit_Home = new javax.swing.JMenu();
        mit_Administrar = new javax.swing.JMenu();
        mit_mantenimientos = new javax.swing.JMenuItem();
        mit_bombas = new javax.swing.JMenuItem();
        mit_usuarios = new javax.swing.JMenuItem();
        mit_reportes = new javax.swing.JMenu();
        mit_generarReporte = new javax.swing.JMenuItem();
        mit_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jdp_escritorio.setBackground(null);
        jdp_escritorio.setOpaque(false);
        jdp_escritorio.setPreferredSize(new java.awt.Dimension(850, 500));

        pnl_principal.setBackground(null);
        pnl_principal.setOpaque(false);
        pnl_principal.setPreferredSize(new java.awt.Dimension(850, 500));

        pnl_dashboard.setBackground(null);
        pnl_dashboard.setOpaque(false);

        pnl_titulo.setBackground(null);
        pnl_titulo.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));
        pnl_titulo.setOpaque(false);

        lbl_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/alarma.png"))); // NOI18N
        lbl_titulo.setText("Resumen de Alarmas");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_titulo)
                .addContainerGap())
        );

        pnl_tabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Alarmas"));
        pnl_tabla.setOpaque(false);

        pnl_content.setOpaque(false);

        tbl_resumenReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_resumenReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Point ID", "Descripcion", "Valor", "Fuera de Servicio", "Reporte"
            }
        ));
        tbl_resumenReportes.setOpaque(false);
        pnl_content.setViewportView(tbl_resumenReportes);

        javax.swing.GroupLayout pnl_tablaLayout = new javax.swing.GroupLayout(pnl_tabla);
        pnl_tabla.setLayout(pnl_tablaLayout);
        pnl_tablaLayout.setHorizontalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_tablaLayout.setVerticalGroup(
            pnl_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_dashboardLayout = new javax.swing.GroupLayout(pnl_dashboard);
        pnl_dashboard.setLayout(pnl_dashboardLayout);
        pnl_dashboardLayout.setHorizontalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_dashboardLayout.createSequentialGroup()
                        .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_dashboardLayout.setVerticalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_dashboardLayout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdp_escritorioLayout = new javax.swing.GroupLayout(jdp_escritorio);
        jdp_escritorio.setLayout(jdp_escritorioLayout);
        jdp_escritorioLayout.setHorizontalGroup(
            jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdp_escritorioLayout.setVerticalGroup(
            jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jdp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdp_escritorio.setLayer(pnl_principal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        men_menu.setMaximumSize(new java.awt.Dimension(172, 32769));
        men_menu.setPreferredSize(new java.awt.Dimension(172, 21));
        men_menu.setRequestFocusEnabled(false);

        mit_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/home.png"))); // NOI18N
        mit_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mit_HomeMouseClicked(evt);
            }
        });
        men_menu.add(mit_Home);

        mit_Administrar.setText("Administrar");

        mit_mantenimientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mit_mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/menu_mantenimientos.png"))); // NOI18N
        mit_mantenimientos.setText("Mantenimiento");
        mit_mantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_mantenimientosActionPerformed(evt);
            }
        });
        mit_Administrar.add(mit_mantenimientos);

        mit_bombas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mit_bombas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/menu_bombas.png"))); // NOI18N
        mit_bombas.setText("Bombas");
        mit_bombas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_bombasActionPerformed(evt);
            }
        });
        mit_Administrar.add(mit_bombas);

        mit_usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mit_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/menu_usuarios.png"))); // NOI18N
        mit_usuarios.setText("Usuarios");
        mit_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_usuariosActionPerformed(evt);
            }
        });
        mit_Administrar.add(mit_usuarios);

        men_menu.add(mit_Administrar);

        mit_reportes.setText("Reportes");

        mit_generarReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mit_generarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/menu_reporte.png"))); // NOI18N
        mit_generarReporte.setText("Generar reporte");
        mit_generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_generarReporteActionPerformed(evt);
            }
        });
        mit_reportes.add(mit_generarReporte);

        men_menu.add(mit_reportes);

        mit_salir.setText("Salir");
        mit_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mit_salirMouseClicked(evt);
            }
        });
        men_menu.add(mit_salir);

        setJMenuBar(men_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mit_mantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_mantenimientosActionPerformed

        uiAgregarTipoMantenimiento = new UIAgregarTipoMantenimiento();
        jdp_escritorio.add(uiAgregarTipoMantenimiento);
        uiMantenimientos.setUIAgregarTipoMantenimiento(uiAgregarTipoMantenimiento);
        cambiapanel(enm_paneles.UIMANTENIMIENTOS);
        
    }//GEN-LAST:event_mit_mantenimientosActionPerformed

    private void mit_bombasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_bombasActionPerformed
        uiAgregarBomba = new UIAgregarBomba(1);
        jdp_escritorio.add(uiAgregarBomba);
        uiBombas.setUIAgregarBomba(uiAgregarBomba);
        cambiapanel(enm_paneles.UIBOMBAS);
    }//GEN-LAST:event_mit_bombasActionPerformed

    private void mit_generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_generarReporteActionPerformed
        cambiapanel(enm_paneles.UIGENERARREPORTES);
    }//GEN-LAST:event_mit_generarReporteActionPerformed

    private void mit_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_usuariosActionPerformed
        uiAgregarUsuario = new UIAgregarUsuario();
        jdp_escritorio.add(uiAgregarUsuario);
        uiUsuarios.setUIAgregarUsuario(uiAgregarUsuario);
        cambiapanel(enm_paneles.UIUSUARIOS);
    }//GEN-LAST:event_mit_usuariosActionPerformed

    private void mit_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mit_salirMouseClicked
        //this.setVisible(false);
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_mit_salirMouseClicked

    private void mit_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mit_HomeMouseClicked
        cambiapanel(enm_paneles.UIDASHBOARD);
    }//GEN-LAST:event_mit_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdp_escritorio;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JMenuBar men_menu;
    private javax.swing.JMenu mit_Administrar;
    private javax.swing.JMenu mit_Home;
    private javax.swing.JMenuItem mit_bombas;
    private javax.swing.JMenuItem mit_generarReporte;
    private javax.swing.JMenuItem mit_mantenimientos;
    private javax.swing.JMenu mit_reportes;
    private javax.swing.JMenu mit_salir;
    private javax.swing.JMenuItem mit_usuarios;
    private javax.swing.JScrollPane pnl_content;
    public javax.swing.JPanel pnl_dashboard;
    public javax.swing.JPanel pnl_principal;
    protected javax.swing.JPanel pnl_tabla;
    protected javax.swing.JPanel pnl_titulo;
    private javax.swing.JTable tbl_resumenReportes;
    // End of variables declaration//GEN-END:variables

    //Instanacia de las vistas
    public UIMantenimientos uiMantenimientos;
    public UIAgregarTipoMantenimiento uiAgregarTipoMantenimiento;
    public UIBombas uiBombas;
    public UIAgregarBomba uiAgregarBomba;
    public UIUsuarios uiUsuarios;
    public UIAgregarUsuario uiAgregarUsuario;
    public UINuevoReporte uiNuevoReporte;
    public UIGenerarReporte uiGenerarReporte;
    
    //Instanacia del Controlador
    Dashboard dashboard;
    
    //CardLayout para la administración de las vistas
    CardLayout card;
    
    //Imagen de fondo
    ImagenPanel imagenFondo;
    
    private void iniciarVentanas() {
        //InicializarControlador
        dashboard = new Dashboard();
        
        //Inicializar vistas
        uiMantenimientos = new UIMantenimientos(this);
        uiBombas = new UIBombas(this);
        uiUsuarios = new UIUsuarios(this);
        uiGenerarReporte = new UIGenerarReporte(this);
        uiNuevoReporte = new UINuevoReporte();
                
        //Agregar los paneles al CardLayout
        card = new CardLayout();
        /*card.addLayoutComponent(uiUsuarios,"uiUsuarios");
        card.addLayoutComponent(uiBombas,"uiBombas");
        card.addLayoutComponent(pnl_dashboard,"uiDashboard");
        card.addLayoutComponent(uiMantenimientos,"uiMantenimientos");
        card.addLayoutComponent(uiGenerarReporte,"uiGenerarReportes");*/
        card.addLayoutComponent(uiUsuarios,enm_paneles.UIUSUARIOS.toString());
        card.addLayoutComponent(uiBombas,enm_paneles.UIBOMBAS.toString());
        card.addLayoutComponent(pnl_dashboard,enm_paneles.UIDASHBOARD.toString());
        card.addLayoutComponent(uiMantenimientos,enm_paneles.UIMANTENIMIENTOS.toString());
        card.addLayoutComponent(uiGenerarReporte,enm_paneles.UIGENERARREPORTES.toString());
        
        //Agregar las vistas al panel principal
        pnl_principal.add(uiUsuarios);
        pnl_principal.add(uiBombas);
        pnl_principal.add(uiMantenimientos);
        pnl_principal.add(uiGenerarReporte);
        
        pnl_principal.setLayout(card);
        card.show(pnl_principal, enm_paneles.UIDASHBOARD.toString());
        
        //Definir imagen de fondo
        imagenFondo = new ImagenPanel("/sisup/recursos/fondo_principal.png");
        imagenFondo.setSize(new java.awt.Dimension(850, 500));
        imagenFondo.setVisible(true);
        jdp_escritorio.add(imagenFondo);
        imagenFondo.add(pnl_principal);
        
        //Definir el acceso a la administracion
        //if (sesion.usuario.rol != enum_roles.administrador)
        //mit_Administrar.setVisible(false);
        
        //Alineación de nombre de usuario a la derecha
        javax.swing.JMenu mit_nombreUsuario = new javax.swing.JMenu();
        mit_nombreUsuario.setText("Bienvenido, ");
        men_menu.add(Box.createHorizontalGlue());
        men_menu.add(mit_nombreUsuario);
        
        this.setLocationRelativeTo(null);
    }

    public Rectangle centrarJInternalFrame(int ancho, int alto) {
        int x = (this.getWidth() - ancho) / 2;
        int y = (this.getHeight()- alto) / 2;
        return new Rectangle(x, y, ancho, alto);
    }
    
    public void cambiapanel(enm_paneles panel){
        card.show(pnl_principal, panel.toString());
    }
    
    public enum enm_paneles{
        UIMANTENIMIENTOS,
        UIUSUARIOS,
        UIBOMBAS,
        UIDASHBOARD,
        UIGENERARREPORTES;
    }
    
}
