/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sisup.ui;

import javax.swing.SwingConstants;
import sisup.clases.Falla;
import sisup.controladores.ReportesControlador;

/**
 *
 * @author Liz
 */
public class UINuevoReporte2 extends javax.swing.JPanel {

    /**
     * Creates new form UINuevoReporte2
     */
    public UINuevoReporte2() {
        initComponents();
        reportesControlador = new ReportesControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_content = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_NuevoReporte = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_registro = new javax.swing.JLabel();
        lbl_parada = new javax.swing.JLabel();
        lbl_arranque = new javax.swing.JLabel();
        lbl_causa = new javax.swing.JLabel();
        lbl_tfds1 = new javax.swing.JLabel();
        lbl_tfds2 = new javax.swing.JLabel();
        lbl_observacion = new javax.swing.JLabel();
        txt_registro = new javax.swing.JLabel();
        txt_parada = new javax.swing.JLabel();
        txt_arranque = new javax.swing.JLabel();
        txt_tfds = new javax.swing.JLabel();
        cmb_causa = new javax.swing.JComboBox();
        txt_ScrollObservacion = new javax.swing.JScrollPane();
        txt_observacion = new javax.swing.JTextArea();
        pnl_accion = new javax.swing.JPanel();
        btn_atras = new javax.swing.JButton();
        btn_atras1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(850, 521));

        lbl_NuevoReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/nuevoReporte.png"))); // NOI18N
        lbl_NuevoReporte.setText("Visualizar Reporte");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NuevoReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NuevoReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Reporte"));

        lbl_registro.setText("Registro:");

        lbl_parada.setText("Parada:");

        lbl_arranque.setText("Arranque:");

        lbl_causa.setText("Causa:");

        lbl_tfds1.setText("Tiempo fuera");

        lbl_tfds2.setText("de Servicio:");

        lbl_observacion.setText("Observación:");

        txt_registro.setText("XXX");

        txt_parada.setText("dd/mm/aaaa");

        txt_arranque.setText("dd/mm/aaaa");

        txt_tfds.setText("tt");

        cmb_causa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_observacion.setColumns(20);
        txt_observacion.setRows(5);
        txt_ScrollObservacion.setViewportView(txt_observacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_registro)
                    .addComponent(lbl_parada)
                    .addComponent(lbl_arranque)
                    .addComponent(lbl_tfds1)
                    .addComponent(lbl_tfds2))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_arranque)
                    .addComponent(txt_tfds)
                    .addComponent(txt_parada)
                    .addComponent(txt_registro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_causa)
                        .addGap(40, 40, 40)
                        .addComponent(cmb_causa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_observacion)
                    .addComponent(txt_ScrollObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_registro)
                    .addComponent(txt_registro)
                    .addComponent(lbl_causa)
                    .addComponent(cmb_causa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_parada)
                            .addComponent(txt_parada))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_arranque)
                            .addComponent(txt_arranque))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tfds1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_tfds2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txt_tfds)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_observacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ScrollObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))))
        );

        btn_atras.setBackground(new java.awt.Color(204, 204, 255));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/atras.png"))); // NOI18N
        btn_atras.setText("Atrás");
        btn_atras.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_atras.setBorderPainted(false);
        btn_atras.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_atras.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_atras.setOpaque(false);
        btn_atras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_atras.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        btn_atras1.setBackground(new java.awt.Color(204, 204, 255));
        btn_atras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/atras.png"))); // NOI18N
        btn_atras1.setText("Atrás");
        btn_atras1.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_atras1.setBorderPainted(false);
        btn_atras1.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_atras1.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_atras1.setOpaque(false);
        btn_atras1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_atras1.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_accionLayout = new javax.swing.GroupLayout(pnl_accion);
        pnl_accion.setLayout(pnl_accionLayout);
        pnl_accionLayout.setHorizontalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_atras)
                .addGap(18, 18, 18)
                .addComponent(btn_atras1)
                .addContainerGap())
        );
        pnl_accionLayout.setVerticalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atras)
                    .addComponent(btn_atras1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_contentLayout = new javax.swing.GroupLayout(pnl_content);
        pnl_content.setLayout(pnl_contentLayout);
        pnl_contentLayout.setHorizontalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentLayout.createSequentialGroup()
                .addGroup(pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnl_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_contentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnl_accion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_contentLayout.setVerticalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        crearReporte();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_atras1;
    private javax.swing.JComboBox cmb_causa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_NuevoReporte;
    private javax.swing.JLabel lbl_arranque;
    private javax.swing.JLabel lbl_causa;
    private javax.swing.JLabel lbl_observacion;
    private javax.swing.JLabel lbl_parada;
    private javax.swing.JLabel lbl_registro;
    private javax.swing.JLabel lbl_tfds1;
    private javax.swing.JLabel lbl_tfds2;
    private javax.swing.JPanel pnl_accion;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_titulo;
    private javax.swing.JScrollPane txt_ScrollObservacion;
    private javax.swing.JLabel txt_arranque;
    private javax.swing.JTextArea txt_observacion;
    private javax.swing.JLabel txt_parada;
    private javax.swing.JLabel txt_registro;
    private javax.swing.JLabel txt_tfds;
    // End of variables declaration//GEN-END:variables

    UIDashboard padre;
    ReportesControlador reportesControlador;
    
    private void mostrarDatosReporte(Falla falla){
        
    }

    private void crearReporte() {
        padre.cambiapanel(UIDashboard.enm_paneles.UIDASHBOARD);
    }
    
    public void setModoFalla(Falla falla){
        if(falla.getEstatus().equals("Activa"))
            mostrarFallaActiva();
        else if(falla.getEstatus().equals("Controlada"))
            mostrarFallaControlada();
        else mostrarFallaCerrada();
    }

    private void mostrarFallaActiva() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void mostrarFallaControlada() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void mostrarFallaCerrada() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
