/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sisup.ui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import sisup.controladores.UsuariosControlador;

/**
 *
 * @author Liz
 */
public class UIUsuarios extends javax.swing.JPanel {
    private final UIDashboard padre;
    private UsuariosControlador usuarios;
    
    /**
     * Creates new form UIUsuariosControlador
     * @param padre
     */
    public UIUsuarios(final UIDashboard padre) {
        super();
        this.padre = padre;
        initComponents();
        CargarTablaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_usuarios = new javax.swing.JPanel();
        pnl_titulo = new javax.swing.JPanel();
        lbl_administrarUsuarios = new javax.swing.JLabel();
        pnl_content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        pnl_accion = new javax.swing.JPanel();
        btn_atras = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();

        setBackground(null);
        setOpaque(false);

        pnl_usuarios.setOpaque(false);
        pnl_usuarios.setPreferredSize(new java.awt.Dimension(800, 500));
        pnl_usuarios.setRequestFocusEnabled(false);

        pnl_titulo.setBackground(null);
        pnl_titulo.setOpaque(false);

        lbl_administrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/administrarUsuarios.png"))); // NOI18N
        lbl_administrarUsuarios.setText("Administrar Usuarios");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_administrarUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_administrarUsuarios))
        );

        pnl_content.setBackground(null);
        pnl_content.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios registrados"));
        pnl_content.setOpaque(false);
        pnl_content.setPreferredSize(new java.awt.Dimension(780, 313));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 64));

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Login", "Cargo", "Estatus", "Acción"
            }
        ));
        jScrollPane1.setViewportView(tbl_usuarios);

        javax.swing.GroupLayout pnl_contentLayout = new javax.swing.GroupLayout(pnl_content);
        pnl_content.setLayout(pnl_contentLayout);
        pnl_contentLayout.setHorizontalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_contentLayout.setVerticalGroup(
            pnl_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );

        pnl_accion.setBackground(null);
        pnl_accion.setOpaque(false);

        btn_atras.setBackground(new java.awt.Color(204, 204, 255));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/atras.png"))); // NOI18N
        btn_atras.setText("Atrás");
        btn_atras.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_atras.setBorderPainted(false);
        btn_atras.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_atras.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_atras.setOpaque(false);
        btn_atras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_atras.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(204, 204, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisup/recursos/agregarNuevoUsuario.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        btn_agregar.setBorderPainted(false);
        btn_agregar.setFocusPainted(false);
        btn_agregar.setFocusable(false);
        btn_agregar.setHorizontalTextPosition(SwingConstants.CENTER);
        btn_agregar.setMargin(new java.awt.Insets(14, 14, 14, 14));
        btn_agregar.setOpaque(false);
        btn_agregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.setVerticalTextPosition(SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_accionLayout = new javax.swing.GroupLayout(pnl_accion);
        pnl_accion.setLayout(pnl_accionLayout);
        pnl_accionLayout.setHorizontalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_accionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar)
                .addGap(18, 18, 18)
                .addComponent(btn_atras)
                .addContainerGap())
        );
        pnl_accionLayout.setVerticalGroup(
            pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_accionLayout.createSequentialGroup()
                .addGroup(pnl_accionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atras)
                    .addComponent(btn_agregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_usuariosLayout = new javax.swing.GroupLayout(pnl_usuarios);
        pnl_usuarios.setLayout(pnl_usuariosLayout);
        pnl_usuariosLayout.setHorizontalGroup(
            pnl_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_accion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_usuariosLayout.setVerticalGroup(
            pnl_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_content, javax.swing.GroupLayout.PREFERRED_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        padre.cambiapanel(UIDashboard.enm_paneles.UIDASHBOARD);
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        
        padre.cambiapanel(UIDashboard.enm_paneles.UIAGREGARUSUARIO);
    }//GEN-LAST:event_btn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_administrarUsuarios;
    private javax.swing.JPanel pnl_accion;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_titulo;
    public javax.swing.JPanel pnl_usuarios;
    private javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
    

    public void CargarTablaUsuarios() {
        if (usuarios == null) usuarios = new UsuariosControlador();

        Object[][] data = usuarios.getListaUsuarios();
        
        if(data.length != 0){
            String[] columnNames = {"Nombre", "Login", "Cargo", "Estatus", "Acción"};

            DefaultTableModel model = new DefaultTableModel(data, columnNames);
            JTable table2 = new JTable(model);

            Action delete = new AbstractAction()
            {
                public void actionPerformed(ActionEvent e)
                {
                    JTable table = (JTable)e.getSource();
                    int modelRow = Integer.valueOf( e.getActionCommand());
                    //((DefaultTableModel)table.getModel()).removeRow(modelRow);
                    String var = table.getModel().getValueAt(modelRow, 0).toString();
                    String ac = e.getActionCommand();
                    padre.uiAgregarUsuario.setModoEditar(usuarios.getUsuarioEditar(modelRow));
                    padre.cambiapanel(UIDashboard.enm_paneles.UIAGREGARUSUARIO);
                }
            };

            ButtonColumn buttonColumn = new ButtonColumn(table2, delete, 4);
            buttonColumn.setMnemonic(KeyEvent.VK_D);

            JScrollPane scroll = new JScrollPane(table2);
            scroll.setPreferredSize(new java.awt.Dimension(400, 200));
            pnl_content.add(scroll);
            scroll.setVisible(true);
            jScrollPane1.setVisible(false);
            scroll.setBounds(30, 30, 400, 200);
        }
    }
    
}
